currency_country_map = {
    "AUD": {"country_code": "AU", "country_name": "Australia"},
    "BGN": {"country_code": "BG", "country_name": "Bulgaria"},
    "BRL": {"country_code": "BR", "country_name": "Brazil"},
    "CAD": {"country_code": "CA", "country_name": "Canada"},
    "CHF": {"country_code": "CH", "country_name": "Switzerland"},
    "CNY": {"country_code": "CN", "country_name": "China"},
    "CZK": {"country_code": "CZ", "country_name": "Czech Republic"},
    "DKK": {"country_code": "DK", "country_name": "Denmark"},
    "GBP": {"country_code": "GB", "country_name": "United Kingdom"},
    "HUF": {"country_code": "HU", "country_name": "Hungary"},
    "IDR": {"country_code": "ID", "country_name": "Indonesia"},
    "ILS": {"country_code": "IL", "country_name": "Israel"},
    "INR": {"country_code": "IN", "country_name": "India"},
    "JPY": {"country_code": "JP", "country_name": "Japan"},
    "KRW": {"country_code": "KR", "country_name": "South Korea"},
    "MXN": {"country_code": "MX", "country_name": "Mexico"},
    "MYR": {"country_code": "MY", "country_name": "Malaysia"},
    "NOK": {"country_code": "NO", "country_name": "Norway"},
    "NZD": {"country_code": "NZ", "country_name": "New Zealand"},
    "PHP": {"country_code": "PH", "country_name": "Philippines"},
    "PLN": {"country_code": "PL", "country_name": "Poland"},
    "RON": {"country_code": "RO", "country_name": "Romania"},
    "SEK": {"country_code": "SE", "country_name": "Sweden"},
    "SGD": {"country_code": "SG", "country_name": "Singapore"},
    "THB": {"country_code": "TH", "country_name": "Thailand"},
    "TRY": {"country_code": "TR", "country_name": "Turkey"},
    "ZAR": {"country_code": "ZA", "country_name": "South Africa"},
    "USD": {"country_code": "US", "country_name": "United States"},
    "EUR": {"country_code": "EU", "country_name": "European Union"},
}
